In [65]:
import pandas as pd

In [66]:
df = pd.read_csv('./data/auto.csv', index_col='ID')
df

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
4    E34877152RUS      Ford Focus     2.0   6100.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[931 rows x 5 columns]

In [67]:
df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

In [68]:
df.drop_duplicates(
    subset=['CarNumber', 'Make_n_model', 'Fines'],
    keep='last',
    inplace=True
)

In [69]:
df

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
5    92918M178RUS      Ford Focus     1.0   5700.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[725 rows x 5 columns]

In [70]:
df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

In [71]:
df.isna().sum()

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

In [72]:
df.dropna(axis=1, thresh=len(df)-500, inplace=True)
df.isna().sum()

CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

In [73]:
df['Refund'] = df['Refund'].ffill()
df.isna().sum()

CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

In [74]:
df['Fines'] = df['Fines'].fillna(df['Fines'].mean())
df.isna().sum()

CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

In [75]:
df[['Make', 'Model']] = df['Make_n_model'].apply(lambda x: pd.Series(str(x).split(' ', 1)))

In [76]:
df

        CarNumber    Make_n_model  Refund         Fines    Make    Model
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.000000    Ford    Focus
1     E432XX77RUS    Toyota Camry     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS      Ford Focus     1.0   2100.000000    Ford    Focus
3    X582HE161RUS      Ford Focus     2.0   2000.000000    Ford    Focus
5    92918M178RUS      Ford Focus     1.0   5700.000000    Ford    Focus
..            ...             ...     ...           ...     ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.000000    Ford    Focus
927  M0309X197RUS      Ford Focus     1.0  22300.000000    Ford    Focus
928  O673E8197RUS      Ford Focus     2.0    600.000000    Ford    Focus
929  8610T8154RUS      Ford Focus     1.0   2000.000000    Ford    Focus
930  H419XE197RUS  Toyota Corolla     2.0   8594.586466  Toyota  Corolla

[725 rows x 6 columns]

In [78]:
df.drop('Make_n_model', axis=1, inplace=True)
df

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [79]:
df.to_json('./data/auto.json', orient='records', force_ascii=False)