In [1]:
import pandas as pd

views = pd.read_csv('../data/feed-views.log', sep='\t', names=['datetime', 'user'], header=None)

views

                        datetime       user
0     2020-04-17 12:01:08.463179      artem
1     2020-04-17 12:01:23.743946      artem
2     2020-04-17 12:27:30.646665      artem
3     2020-04-17 12:35:44.884757      artem
4     2020-04-17 12:35:52.735016      artem
...                          ...        ...
1071  2020-05-21 18:45:20.441142  valentina
1072  2020-05-21 23:03:06.457819      maxim
1073  2020-05-21 23:23:49.995349      pavel
1074  2020-05-21 23:49:22.386789      artem
1075  2020-05-22 10:36:14.662600      artem

[1076 rows x 2 columns]

In [2]:
views['datetime'] = pd.to_datetime(views['datetime'])
views['year'] = views['datetime'].dt.year
views['month'] = views['datetime'].dt.month
views['day'] = views['datetime'].dt.day
views['hour'] = views['datetime'].dt.hour
views['minute'] = views['datetime'].dt.minute
views['second'] = views['datetime'].dt.second

In [3]:
views.head()

                    datetime   user  year  month  day  hour  minute  second
0 2020-04-17 12:01:08.463179  artem  2020      4   17    12       1       8
1 2020-04-17 12:01:23.743946  artem  2020      4   17    12       1      23
2 2020-04-17 12:27:30.646665  artem  2020      4   17    12      27      30
3 2020-04-17 12:35:44.884757  artem  2020      4   17    12      35      44
4 2020-04-17 12:35:52.735016  artem  2020      4   17    12      35      52

In [4]:
bins = [0, 4, 7, 11, 17, 20, 24]
labels = [
    'night',
    'early morning',
    'morning',
    'afternoon',
    'early evening',
    'evening'
]

views['daytime'] = pd.cut(
    views['hour'],
    bins=bins,
    labels=labels,
    right=False
)

In [5]:
views.head()

,datetime,user,year,month,day,hour,minute,second,daytime
0,2020-04-17 12:01:08.463179,artem,2020,4,17,12,1,8,afternoon
1,2020-04-17 12:01:23.743946,artem,2020,4,17,12,1,23,afternoon
2,2020-04-17 12:27:30.646665,artem,2020,4,17,12,27,30,afternoon
3,2020-04-17 12:35:44.884757,artem,2020,4,17,12,35,44,afternoon
4,2020-04-17 12:35:52.735016,artem,2020,4,17,12,35,52,afternoon

In [6]:
views.set_index('user', inplace=True)

In [7]:
views.head()

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon

In [8]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [9]:
views['daytime'].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

In [10]:
views.sort_values(by=['hour', 'minute', 'second'], inplace=True)

In [22]:
print(f'Минимум часов: {views['hour'].min()}, Максимум часов: {views['hour'].max()}')

Минимум часов: 0, Максимум часов: 23

In [19]:
views['daytime'].mode()

0    evening
Name: daytime, dtype: category
Categories (6, str): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

In [23]:
views[views['daytime'] == 'night']['hour'].max()

np.int32(3)

In [24]:
morning = views[views['daytime'] == 'morning']
min_hour = morning['hour'].min()

morning[morning['hour'] == min_hour].head(1)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning

In [28]:
views['hour'].mode()

0    22
Name: hour, dtype: int32

In [26]:
views['daytime'].mode()

0    evening
Name: daytime, dtype: category
Categories (6, str): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

In [36]:
views.nsmallest(3, 'hour')[['hour']]

           hour
user
valentina     0
valentina     0
pavel         0

In [30]:
views.nlargest(3, 'hour')[['hour']]

           hour
user
ekaterina    23
ekaterina    23
ekaterina    23

In [31]:
views.describe()

,datetime,year,month,day,hour,minute,second
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302553,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:44:34.749530,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506

In [33]:
desc = views['hour'].describe()

iqr = desc['75%'] - desc['25%']
iqr

np.float64(9.0)